# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_tab.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MyProjectTab(object):
    def setupUi(self, MyProjectTab):
        MyProjectTab.setObjectName("MyProjectTab")
        MyProjectTab.resize(1222, 1038)
        self.verticalLayout = QtWidgets.QVBoxLayout(MyProjectTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(MyProjectTab)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.namelabel = QtWidgets.QLabel(self.groupBox)
        self.namelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.namelabel.setObjectName("namelabel")
        self.gridLayout.addWidget(self.namelabel, 0, 0, 1, 1)
        self.pdir_Button = QtWidgets.QToolButton(self.groupBox)
        self.pdir_Button.setObjectName("pdir_Button")
        self.gridLayout.addWidget(self.pdir_Button, 1, 2, 1, 1)
        self.project_dir = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.project_dir.setFont(font)
        self.project_dir.setObjectName("project_dir")
        self.gridLayout.addWidget(self.project_dir, 1, 1, 1, 1)
        self.project_DB_dir = QtWidgets.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.project_DB_dir.setFont(font)
        self.project_DB_dir.setObjectName("project_DB_dir")
        self.gridLayout.addWidget(self.project_DB_dir, 2, 1, 1, 1)
        self.projDBlabel = QtWidgets.QLabel(self.groupBox)
        self.projDBlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projDBlabel.setObjectName("projDBlabel")
        self.gridLayout.addWidget(self.projDBlabel, 2, 0, 1, 1)
        self.project_name = QtWidgets.QLineEdit(self.groupBox)
        self.project_name.setClearButtonEnabled(False)
        self.project_name.setObjectName("project_name")
        self.gridLayout.addWidget(self.project_name, 0, 1, 1, 1)
        self.dirlabel = QtWidgets.QLabel(self.groupBox)
        self.dirlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dirlabel.setObjectName("dirlabel")
        self.gridLayout.addWidget(self.dirlabel, 1, 0, 1, 1)
        self.pdatabase_Button = QtWidgets.QToolButton(self.groupBox)
        self.pdatabase_Button.setObjectName("pdatabase_Button")
        self.gridLayout.addWidget(self.pdatabase_Button, 2, 2, 1, 1)
        self.projButtonLayout = QtWidgets.QHBoxLayout()
        self.projButtonLayout.setObjectName("projButtonLayout")
        self.loadfiles_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadfiles_Button.sizePolicy().hasHeightForWidth())
        self.loadfiles_Button.setSizePolicy(sizePolicy)
        self.loadfiles_Button.setObjectName("loadfiles_Button")
        self.projButtonLayout.addWidget(self.loadfiles_Button)
        self.loadProj_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadProj_Button.sizePolicy().hasHeightForWidth())
        self.loadProj_Button.setSizePolicy(sizePolicy)
        self.loadProj_Button.setObjectName("loadProj_Button")
        self.projButtonLayout.addWidget(self.loadProj_Button)
        self.saveProj_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveProj_Button.sizePolicy().hasHeightForWidth())
        self.saveProj_Button.setSizePolicy(sizePolicy)
        self.saveProj_Button.setObjectName("saveProj_Button")
        self.projButtonLayout.addWidget(self.saveProj_Button)
        self.gridLayout.addLayout(self.projButtonLayout, 3, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.commentsLayout = QtWidgets.QVBoxLayout()
        self.commentsLayout.setObjectName("commentsLayout")
        self.comments_label = QtWidgets.QLabel(self.groupBox)
        self.comments_label.setObjectName("comments_label")
        self.commentsLayout.addWidget(self.comments_label)
        self.comments_val = QtWidgets.QTextEdit(self.groupBox)
        self.comments_val.setObjectName("comments_val")
        self.commentsLayout.addWidget(self.comments_val)
        self.horizontalLayout_3.addLayout(self.commentsLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.SampleEnv = QtWidgets.QGroupBox(MyProjectTab)
        self.SampleEnv.setObjectName("SampleEnv")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SampleEnv)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.templabel = QtWidgets.QLabel(self.SampleEnv)
        self.templabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.templabel.setObjectName("templabel")
        self.gridLayout_2.addWidget(self.templabel, 0, 0, 1, 1)
        self.reslabel = QtWidgets.QLabel(self.SampleEnv)
        self.reslabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.reslabel.setObjectName("reslabel")
        self.gridLayout_2.addWidget(self.reslabel, 0, 3, 1, 1)
        self.presslabel = QtWidgets.QLabel(self.SampleEnv)
        self.presslabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.presslabel.setObjectName("presslabel")
        self.gridLayout_2.addWidget(self.presslabel, 1, 0, 1, 1)
        self.press_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.press_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.press_val.setObjectName("press_val")
        self.gridLayout_2.addWidget(self.press_val, 1, 1, 1, 1)
        self.res_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.res_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.res_val.setObjectName("res_val")
        self.gridLayout_2.addWidget(self.res_val, 0, 4, 1, 1)
        self.pathLlabel = QtWidgets.QLabel(self.SampleEnv)
        self.pathLlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathLlabel.setObjectName("pathLlabel")
        self.gridLayout_2.addWidget(self.pathLlabel, 2, 0, 2, 1)
        self.temp_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.temp_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.temp_val.setObjectName("temp_val")
        self.gridLayout_2.addWidget(self.temp_val, 0, 1, 1, 1)
        self.roiLow_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.roiLow_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiLow_val.setObjectName("roiLow_val")
        self.gridLayout_2.addWidget(self.roiLow_val, 4, 1, 2, 1)
        self.apodlabel = QtWidgets.QLabel(self.SampleEnv)
        self.apodlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.apodlabel.setObjectName("apodlabel")
        self.gridLayout_2.addWidget(self.apodlabel, 1, 3, 1, 1)
        self.roiunit_2 = QtWidgets.QLabel(self.SampleEnv)
        self.roiunit_2.setToolTipDuration(-11)
        self.roiunit_2.setObjectName("roiunit_2")
        self.gridLayout_2.addWidget(self.roiunit_2, 5, 5, 1, 1)
        self.apod_val = QtWidgets.QComboBox(self.SampleEnv)
        self.apod_val.setEditable(False)
        self.apod_val.setObjectName("apod_val")
        self.apod_val.addItem("")
        self.apod_val.addItem("")
        self.gridLayout_2.addWidget(self.apod_val, 1, 4, 2, 1)
        self.pathL_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.pathL_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathL_val.setObjectName("pathL_val")
        self.gridLayout_2.addWidget(self.pathL_val, 2, 1, 2, 1)
        self.temp_unit = QtWidgets.QComboBox(self.SampleEnv)
        self.temp_unit.setEditable(False)
        self.temp_unit.setObjectName("temp_unit")
        self.temp_unit.addItem("")
        self.temp_unit.addItem("")
        self.temp_unit.addItem("")
        self.gridLayout_2.addWidget(self.temp_unit, 0, 2, 1, 1)
        self.roiHlabel = QtWidgets.QLabel(self.SampleEnv)
        self.roiHlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiHlabel.setObjectName("roiHlabel")
        self.gridLayout_2.addWidget(self.roiHlabel, 5, 3, 1, 1)
        self.pathL_unit = QtWidgets.QComboBox(self.SampleEnv)
        self.pathL_unit.setEditable(False)
        self.pathL_unit.setObjectName("pathL_unit")
        self.pathL_unit.addItem("")
        self.pathL_unit.addItem("")
        self.gridLayout_2.addWidget(self.pathL_unit, 2, 2, 2, 1)
        self.press_unit = QtWidgets.QComboBox(self.SampleEnv)
        self.press_unit.setEditable(False)
        self.press_unit.setObjectName("press_unit")
        self.press_unit.addItem("")
        self.press_unit.addItem("")
        self.press_unit.addItem("")
        self.press_unit.addItem("")
        self.gridLayout_2.addWidget(self.press_unit, 1, 2, 1, 1)
        self.roiunit = QtWidgets.QLabel(self.SampleEnv)
        self.roiunit.setToolTipDuration(-11)
        self.roiunit.setObjectName("roiunit")
        self.gridLayout_2.addWidget(self.roiunit, 5, 2, 1, 1)
        self.resunit = QtWidgets.QLabel(self.SampleEnv)
        self.resunit.setToolTipDuration(-11)
        self.resunit.setObjectName("resunit")
        self.gridLayout_2.addWidget(self.resunit, 0, 5, 1, 1)
        self.fovlabel = QtWidgets.QLabel(self.SampleEnv)
        self.fovlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fovlabel.setObjectName("fovlabel")
        self.gridLayout_2.addWidget(self.fovlabel, 3, 3, 1, 1)
        self.roiHigh_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.roiHigh_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiHigh_val.setObjectName("roiHigh_val")
        self.gridLayout_2.addWidget(self.roiHigh_val, 5, 4, 1, 1)
        self.fov_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.fov_val.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fov_val.setObjectName("fov_val")
        self.gridLayout_2.addWidget(self.fov_val, 3, 4, 2, 1)
        self.roiLlabel = QtWidgets.QLabel(self.SampleEnv)
        self.roiLlabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiLlabel.setObjectName("roiLlabel")
        self.gridLayout_2.addWidget(self.roiLlabel, 4, 0, 2, 1)
        self.bgfile_val = QtWidgets.QLineEdit(self.SampleEnv)
        self.bgfile_val.setAlignment(QtCore.Qt.AlignCenter)
        self.bgfile_val.setObjectName("bgfile_val")
        self.gridLayout_2.addWidget(self.bgfile_val, 6, 1, 1, 1)
        self.bgFile_Button = QtWidgets.QToolButton(self.SampleEnv)
        self.bgFile_Button.setObjectName("bgFile_Button")
        self.gridLayout_2.addWidget(self.bgFile_Button, 6, 2, 1, 1)
        self.bgfilelabel = QtWidgets.QLabel(self.SampleEnv)
        self.bgfilelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bgfilelabel.setObjectName("bgfilelabel")
        self.gridLayout_2.addWidget(self.bgfilelabel, 6, 0, 1, 1)
        self.ftype_val = QtWidgets.QComboBox(self.SampleEnv)
        self.ftype_val.setEditable(False)
        self.ftype_val.setObjectName("ftype_val")
        self.ftype_val.addItem("")
        self.ftype_val.addItem("")
        self.ftype_val.addItem("")
        self.gridLayout_2.addWidget(self.ftype_val, 6, 4, 1, 1)
        self.ftypelabel = QtWidgets.QLabel(self.SampleEnv)
        self.ftypelabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ftypelabel.setObjectName("ftypelabel")
        self.gridLayout_2.addWidget(self.ftypelabel, 6, 3, 1, 1)
        self.verticalLayout.addWidget(self.SampleEnv)
        self.Components = QtWidgets.QGroupBox(MyProjectTab)
        self.Components.setObjectName("Components")
        self.Component_Layout = QtWidgets.QVBoxLayout(self.Components)
        self.Component_Layout.setObjectName("Component_Layout")
        self.sampleLayout = QtWidgets.QHBoxLayout()
        self.sampleLayout.setObjectName("sampleLayout")
        self.label_4 = QtWidgets.QLabel(self.Components)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.sampleLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.Components)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.sampleLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.Components)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.sampleLayout.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.Components)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.sampleLayout.addWidget(self.label_9)
        self.label = QtWidgets.QLabel(self.Components)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.sampleLayout.addWidget(self.label)
        self.Component_Layout.addLayout(self.sampleLayout)
        self.verticalLayout.addWidget(self.Components)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addComponentButton = QtWidgets.QPushButton(MyProjectTab)
        self.addComponentButton.setObjectName("addComponentButton")
        self.horizontalLayout.addWidget(self.addComponentButton)
        self.fitSpectraButton = QtWidgets.QPushButton(MyProjectTab)
        self.fitSpectraButton.setObjectName("fitSpectraButton")
        self.horizontalLayout.addWidget(self.fitSpectraButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MyProjectTab)
        self.apod_val.setCurrentIndex(0)
        self.temp_unit.setCurrentIndex(0)
        self.pathL_unit.setCurrentIndex(0)
        self.press_unit.setCurrentIndex(0)
        self.ftype_val.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MyProjectTab)

    def retranslateUi(self, MyProjectTab):
        _translate = QtCore.QCoreApplication.translate
        MyProjectTab.setWindowTitle(_translate("MyProjectTab", "Form"))
        self.groupBox.setTitle(_translate("MyProjectTab", "Project"))
        self.namelabel.setText(_translate("MyProjectTab", "Project Name:"))
        self.pdir_Button.setText(_translate("MyProjectTab", "..."))
        self.projDBlabel.setText(_translate("MyProjectTab", "Project Database:"))
        self.dirlabel.setText(_translate("MyProjectTab", "Project Directory:"))
        self.pdatabase_Button.setText(_translate("MyProjectTab", "..."))
        self.loadfiles_Button.setText(_translate("MyProjectTab", "Load Files"))
        self.loadProj_Button.setText(_translate("MyProjectTab", "Load Project"))
        self.saveProj_Button.setText(_translate("MyProjectTab", "Save Project"))
        self.comments_label.setText(_translate("MyProjectTab", "Project Comments"))
        self.comments_val.setPlaceholderText(_translate("MyProjectTab", "comments about the run"))
        self.SampleEnv.setTitle(_translate("MyProjectTab", "Sample Environment and Analysis parameters"))
        self.templabel.setText(_translate("MyProjectTab", "Temperature:"))
        self.reslabel.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Region of intrest</p></body></html>"))
        self.reslabel.setText(_translate("MyProjectTab", "Resolution:"))
        self.presslabel.setText(_translate("MyProjectTab", "Pressure:"))
        self.press_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Total pressure of the system</p></body></html>"))
        self.press_val.setText(_translate("MyProjectTab", "0"))
        self.res_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Pathlength of the spectroscopic beam</p></body></html>"))
        self.res_val.setText(_translate("MyProjectTab", "0"))
        self.pathLlabel.setText(_translate("MyProjectTab", "Pathlength:"))
        self.temp_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Temperature of the system</p><p><br/></p></body></html>"))
        self.temp_val.setText(_translate("MyProjectTab", "0"))
        self.roiLow_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Pathlength of the spectroscopic beam</p></body></html>"))
        self.roiLow_val.setText(_translate("MyProjectTab", "0"))
        self.apodlabel.setText(_translate("MyProjectTab", "Apodization:"))
        self.roiunit_2.setText(_translate("MyProjectTab", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-1</span></p></body></html>"))
        self.apod_val.setCurrentText(_translate("MyProjectTab", "Boxcar"))
        self.apod_val.setItemText(0, _translate("MyProjectTab", "Boxcar"))
        self.apod_val.setItemText(1, _translate("MyProjectTab", "Triangle"))
        self.pathL_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Pathlength of the spectroscopic beam</p></body></html>"))
        self.pathL_val.setText(_translate("MyProjectTab", "0"))
        self.temp_unit.setCurrentText(_translate("MyProjectTab", "K"))
        self.temp_unit.setItemText(0, _translate("MyProjectTab", "K"))
        self.temp_unit.setItemText(1, _translate("MyProjectTab", "C"))
        self.temp_unit.setItemText(2, _translate("MyProjectTab", "F"))
        self.roiHlabel.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Region of intrest</p></body></html>"))
        self.roiHlabel.setText(_translate("MyProjectTab", "ROI high:"))
        self.pathL_unit.setCurrentText(_translate("MyProjectTab", "m"))
        self.pathL_unit.setItemText(0, _translate("MyProjectTab", "m"))
        self.pathL_unit.setItemText(1, _translate("MyProjectTab", "cm"))
        self.press_unit.setCurrentText(_translate("MyProjectTab", "atm"))
        self.press_unit.setItemText(0, _translate("MyProjectTab", "atm"))
        self.press_unit.setItemText(1, _translate("MyProjectTab", "bar"))
        self.press_unit.setItemText(2, _translate("MyProjectTab", "PSI"))
        self.press_unit.setItemText(3, _translate("MyProjectTab", "Pa"))
        self.roiunit.setText(_translate("MyProjectTab", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-1</span></p></body></html>"))
        self.resunit.setText(_translate("MyProjectTab", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">-1</span></p></body></html>"))
        self.fovlabel.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Region of intrest</p></body></html>"))
        self.fovlabel.setText(_translate("MyProjectTab", "FOV:"))
        self.roiHigh_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Pathlength of the spectroscopic beam</p></body></html>"))
        self.roiHigh_val.setText(_translate("MyProjectTab", "0"))
        self.fov_val.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Pathlength of the spectroscopic beam</p></body></html>"))
        self.fov_val.setText(_translate("MyProjectTab", "0"))
        self.roiLlabel.setToolTip(_translate("MyProjectTab", "<html><head/><body><p>Region of intrest</p></body></html>"))
        self.roiLlabel.setText(_translate("MyProjectTab", "ROI low:"))
        self.bgFile_Button.setText(_translate("MyProjectTab", "..."))
        self.bgfilelabel.setText(_translate("MyProjectTab", "BG File:"))
        self.ftype_val.setCurrentText(_translate("MyProjectTab", "Transmission"))
        self.ftype_val.setItemText(0, _translate("MyProjectTab", "Transmission"))
        self.ftype_val.setItemText(1, _translate("MyProjectTab", "Absorbtion (ln)"))
        self.ftype_val.setItemText(2, _translate("MyProjectTab", "Absorbtion(lg)"))
        self.ftypelabel.setText(_translate("MyProjectTab", "File type"))
        self.Components.setTitle(_translate("MyProjectTab", "Sample Composistion"))
        self.label_4.setText(_translate("MyProjectTab", "Compound"))
        self.label_3.setText(_translate("MyProjectTab", "Isotop"))
        self.label_2.setText(_translate("MyProjectTab", "Amount"))
        self.label_9.setText(_translate("MyProjectTab", "Unit"))
        self.addComponentButton.setText(_translate("MyProjectTab", "Add Component"))
        self.fitSpectraButton.setText(_translate("MyProjectTab", "Fit Spectra"))

